[2023-10-03 00:31:59,651] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.create_table_redshift scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03 00:31:59,656] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.create_table_redshift scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03 00:31:59,657] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-03 00:31:59,657] {taskinstance.py:1377} INFO - Starting attempt 3 of 8
[2023-10-03 00:31:59,657] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-03 00:31:59,667] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_table_redshift> on 2023-10-02 00:00:00+00:00
[2023-10-03 00:31:59,670] {standard_task_runner.py:52} INFO - Started process 201 to run task
[2023-10-03 00:31:59,671] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'consultar_info_covid_api', 'create_table_redshift', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/api_covid.py', '--cfg-path', '/tmp/tmplsdtfwlo', '--error-file', '/tmp/tmp88tdzk_x']
[2023-10-03 00:31:59,671] {standard_task_runner.py:80} INFO - Job 292: Subtask create_table_redshift
[2023-10-03 00:31:59,706] {task_command.py:371} INFO - Running <TaskInstance: consultar_info_covid_api.create_table_redshift scheduled__2023-10-02T00:00:00+00:00 [running]> on host 607b1a507b9c
[2023-10-03 00:31:59,756] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Axel Villegas Luna
AIRFLOW_CTX_DAG_ID=consultar_info_covid_api
AIRFLOW_CTX_TASK_ID=create_table_redshift
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-02T00:00:00+00:00
[2023-10-03 00:32:01,420] {python.py:173} INFO - Done. Returned value was: None
[2023-10-03 00:32:01,428] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=consultar_info_covid_api, task_id=create_table_redshift, execution_date=20231002T000000, start_date=20231003T003159, end_date=20231003T003201
[2023-10-03 00:32:01,446] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-03 00:32:01,463] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.holis scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:32:01,463] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.call_api_covid scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:32:01,464] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.delete_data_redshift scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:32:01,464] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.insert_table_redshift scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:32:01,473] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
