[2023-10-03 00:34:14,624] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.create_table_redshift scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03 00:34:14,630] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.create_table_redshift scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03 00:34:14,631] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-03 00:34:14,631] {taskinstance.py:1377} INFO - Starting attempt 4 of 9
[2023-10-03 00:34:14,631] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-03 00:34:14,641] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_table_redshift> on 2023-10-02 00:00:00+00:00
[2023-10-03 00:34:14,643] {standard_task_runner.py:52} INFO - Started process 278 to run task
[2023-10-03 00:34:14,645] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'consultar_info_covid_api', 'create_table_redshift', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '295', '--raw', '--subdir', 'DAGS_FOLDER/api_covid.py', '--cfg-path', '/tmp/tmp68f2t2rf', '--error-file', '/tmp/tmptechw3gv']
[2023-10-03 00:34:14,645] {standard_task_runner.py:80} INFO - Job 295: Subtask create_table_redshift
[2023-10-03 00:34:14,679] {task_command.py:371} INFO - Running <TaskInstance: consultar_info_covid_api.create_table_redshift scheduled__2023-10-02T00:00:00+00:00 [running]> on host 607b1a507b9c
[2023-10-03 00:34:14,724] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Axel Villegas Luna
AIRFLOW_CTX_DAG_ID=consultar_info_covid_api
AIRFLOW_CTX_TASK_ID=create_table_redshift
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-02T00:00:00+00:00
[2023-10-03 00:34:16,358] {python.py:173} INFO - Done. Returned value was: None
[2023-10-03 00:34:16,366] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=consultar_info_covid_api, task_id=create_table_redshift, execution_date=20231002T000000, start_date=20231003T003414, end_date=20231003T003416
[2023-10-03 00:34:16,380] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-03 00:34:16,396] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.holis scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:34:16,397] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.call_api_covid scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:34:16,397] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.delete_data_redshift scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:34:16,398] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.insert_table_redshift scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:34:16,407] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
