[2023-10-03 00:21:18,755] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.call_api_covid scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03 00:21:18,761] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.call_api_covid scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03 00:21:18,761] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-03 00:21:18,761] {taskinstance.py:1377} INFO - Starting attempt 2 of 7
[2023-10-03 00:21:18,762] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-03 00:21:18,772] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): call_api_covid> on 2023-10-02 00:00:00+00:00
[2023-10-03 00:21:18,774] {standard_task_runner.py:52} INFO - Started process 272 to run task
[2023-10-03 00:21:18,776] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'consultar_info_covid_api', 'call_api_covid', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/api_covid.py', '--cfg-path', '/tmp/tmp1otnf7e5', '--error-file', '/tmp/tmp1w5wneru']
[2023-10-03 00:21:18,776] {standard_task_runner.py:80} INFO - Job 286: Subtask call_api_covid
[2023-10-03 00:21:18,811] {task_command.py:371} INFO - Running <TaskInstance: consultar_info_covid_api.call_api_covid scheduled__2023-10-02T00:00:00+00:00 [running]> on host f57de557d52a
[2023-10-03 00:21:18,855] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Axel Villegas Luna
AIRFLOW_CTX_DAG_ID=consultar_info_covid_api
AIRFLOW_CTX_TASK_ID=call_api_covid
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-02T00:00:00+00:00
[2023-10-03 00:21:30,091] {python.py:173} INFO - Done. Returned value was: None
[2023-10-03 00:21:30,099] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=consultar_info_covid_api, task_id=call_api_covid, execution_date=20231002T000000, start_date=20231003T002118, end_date=20231003T002130
[2023-10-03 00:21:30,143] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-03 00:21:30,157] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.holis scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:21:30,166] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
