[2023-10-03 00:19:35,226] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.call_api_covid scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03 00:19:35,231] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.call_api_covid scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2023-10-03 00:19:35,232] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-03 00:19:35,232] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-10-03 00:19:35,232] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-03 00:19:35,243] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): call_api_covid> on 2023-10-02 00:00:00+00:00
[2023-10-03 00:19:35,245] {standard_task_runner.py:52} INFO - Started process 209 to run task
[2023-10-03 00:19:35,247] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'consultar_info_covid_api', 'call_api_covid', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/api_covid.py', '--cfg-path', '/tmp/tmp_4a_9jvs', '--error-file', '/tmp/tmpzy5xekqu']
[2023-10-03 00:19:35,247] {standard_task_runner.py:80} INFO - Job 281: Subtask call_api_covid
[2023-10-03 00:19:35,283] {task_command.py:371} INFO - Running <TaskInstance: consultar_info_covid_api.call_api_covid scheduled__2023-10-02T00:00:00+00:00 [running]> on host f57de557d52a
[2023-10-03 00:19:35,330] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Axel Villegas Luna
AIRFLOW_CTX_DAG_ID=consultar_info_covid_api
AIRFLOW_CTX_TASK_ID=call_api_covid
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-02T00:00:00+00:00
[2023-10-03 00:19:47,548] {python.py:173} INFO - Done. Returned value was: None
[2023-10-03 00:19:47,557] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=consultar_info_covid_api, task_id=call_api_covid, execution_date=20231002T000000, start_date=20231003T001935, end_date=20231003T001947
[2023-10-03 00:19:47,575] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-03 00:19:47,589] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: consultar_info_covid_api.holis scheduled__2023-10-02T00:00:00+00:00 [removed]>' for dag 'consultar_info_covid_api'. Marking it as removed.
[2023-10-03 00:19:47,597] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
