[2023-10-13 18:28:56,854] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-13 18:28:56,859] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-13 18:28:56,860] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-13 18:28:56,860] {taskinstance.py:1377} INFO - Starting attempt 4 of 9
[2023-10-13 18:28:56,860] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-13 18:28:56,871] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_redshift> on 2023-10-12 00:00:00+00:00
[2023-10-13 18:28:56,874] {standard_task_runner.py:52} INFO - Started process 200 to run task
[2023-10-13 18:28:56,876] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'consultar_info_covid_api', 'load_data_redshift', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '359', '--raw', '--subdir', 'DAGS_FOLDER/api_covid.py', '--cfg-path', '/tmp/tmp4pr9w6t5', '--error-file', '/tmp/tmpvtk49y7w']
[2023-10-13 18:28:56,877] {standard_task_runner.py:80} INFO - Job 359: Subtask load_data_redshift
[2023-10-13 18:28:56,914] {task_command.py:371} INFO - Running <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [running]> on host 738c88afe20a
[2023-10-13 18:28:56,959] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Axel Villegas Luna
AIRFLOW_CTX_DAG_ID=consultar_info_covid_api
AIRFLOW_CTX_TASK_ID=load_data_redshift
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-13 18:29:03,978] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:29:14,083] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:29:20,133] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:29:26,722] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:29:34,797] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:29:43,165] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:29:51,487] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:30:00,914] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:30:10,478] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:30:20,329] {logging_mixin.py:115} INFO - Exito
[2023-10-13 18:30:20,329] {python.py:173} INFO - Done. Returned value was: None
[2023-10-13 18:30:20,339] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=consultar_info_covid_api, task_id=load_data_redshift, execution_date=20231012T000000, start_date=20231013T182856, end_date=20231013T183020
[2023-10-13 18:30:20,358] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-13 18:30:20,377] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
