[2023-10-13 18:25:11,330] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-13 18:25:11,336] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2023-10-13 18:25:11,336] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-13 18:25:11,337] {taskinstance.py:1377} INFO - Starting attempt 3 of 8
[2023-10-13 18:25:11,337] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-13 18:25:11,348] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load_data_redshift> on 2023-10-12 00:00:00+00:00
[2023-10-13 18:25:11,351] {standard_task_runner.py:52} INFO - Started process 200 to run task
[2023-10-13 18:25:11,352] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'consultar_info_covid_api', 'load_data_redshift', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/api_covid.py', '--cfg-path', '/tmp/tmpp597rho9', '--error-file', '/tmp/tmpyjnvu93b']
[2023-10-13 18:25:11,353] {standard_task_runner.py:80} INFO - Job 355: Subtask load_data_redshift
[2023-10-13 18:25:11,392] {task_command.py:371} INFO - Running <TaskInstance: consultar_info_covid_api.load_data_redshift scheduled__2023-10-12T00:00:00+00:00 [running]> on host 738c88afe20a
[2023-10-13 18:25:11,442] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Axel Villegas Luna
AIRFLOW_CTX_DAG_ID=consultar_info_covid_api
AIRFLOW_CTX_TASK_ID=load_data_redshift
AIRFLOW_CTX_EXECUTION_DATE=2023-10-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-12T00:00:00+00:00
[2023-10-13 18:25:16,202] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:25:16,202] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:25:21,340] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:25:21,341] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:25:26,284] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:25:26,284] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:25:31,900] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:25:31,900] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:25:37,981] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:25:37,981] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:25:45,379] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:25:45,379] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:25:52,633] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:25:52,633] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:26:00,571] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:26:00,571] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:26:09,137] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:26:09,138] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:26:18,659] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xf3' in position 55: ordinal not in range(128)
[2023-10-13 18:26:18,659] {logging_mixin.py:115} INFO - Failure
[2023-10-13 18:26:18,659] {python.py:173} INFO - Done. Returned value was: None
[2023-10-13 18:26:18,669] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=consultar_info_covid_api, task_id=load_data_redshift, execution_date=20231012T000000, start_date=20231013T182511, end_date=20231013T182618
[2023-10-13 18:26:18,714] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-10-13 18:26:18,732] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
